#+TITLE: CMPM 118 Github Syllabus
#+AUTHOR: Leilani Gilpin
#+MACRO: quarter Fall 2026

* CMPM 118 (AIEA) - Collaborative Research Experiences in the AI Explainability and Accountability (AIEA) Lab
The full syllabus for the course on Google Drive (link TBD).

There are two tracks:
1.  [Auditor track](auditor-onboarding/) this is for *new
   undergraduate students* that are interested in joining the AIEA
   Lab.  To be eligible to join the lab as an *active member* (see
   below) you must complete the 10 onboarding tasks within a quarter.
2. [Active track](active-research/) this is for *ongoing undergraduate
   students* that have (a) taken at least one quarter for CMPM 118
   prior *and* (b) completed the 10 onboarding tasks for a project
   within a quarter.  
** Instructor Information
** Course Overview

** Projects
The available projects for {{{quarter}}} are:
- [[file:onboarding/proj_ai_ethics/][AI Ethics]]
- [[file:onboarding/proj_llm_logic_nesy/][NeuroSymbolic AI (NeSy)]]
- [[file:onboarding/proj_neural_explanations_llms/][Neural Explanations for LLMs]]
- [[file:onboarding/proj_neural_explanations_llms/neural_explanations_vision/][Neural Explanations for Computer Vision]]
- [[file:onboarding/proj_robustifying_avs/][Robustifying Autonomous Vehicles (AVs)]]
- [[file:onboarding/proj_self_explaining_neural_networks/][Self-Explaining Neural Networks (SENNs)]]

Project leads who are creating or revising onboarding tasks should use the [[file:onboarding/task_templates/][project task-authoring guide and templates]].
